version: "3.9"
services:
  db:
    image: postgres:15.4
    volumes:
      - ./postgres_db:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: keycloak
    ports:
      - 5432:5432
  keycloak:
    depends_on:
      - db
    image: quay.io/keycloak/keycloak:25.0.0
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_DB: postgres
      KC_DB_URL_HOST: db
      KC_DB_URL_PORT: 5432
      KC_DB_USERNAME: postgres
      KC_DB_PASSWORD: postgres
    command: start-dev --verbose
    ports:
      - 8080:8080